@MmorpgApi_HostAddress = https://localhost:7250
@LikId = 222

GET {{MmorpgApi_HostAddress}}/Strelac/PreuzmiStrelca/207
Accept: application/json
###

POST {{MmorpgApi_HostAddress}}/Strelac/DodajStrelca/{{LikId}} HTTP/1.1
content-type: application/json

{
  "lukIliSamostrel": 0
}
###

PUT {{MmorpgApi_HostAddress}}/Strelac/AzurirajStrelca/ HTTP/1.1
Content-Type: application/json

{
  "id": 207,
  "lukIliSamostrel": 1
}
###

DELETE {{MmorpgApi_HostAddress}}/Strelac/ObrisiStrelca/207 HTTP/1.1
Content-Type: application/json
###