@MmorpgApi_HostAddress = https://localhost:7250
@LikId = 222

GET {{MmorpgApi_HostAddress}}/Svestenik/PreuzmiSvestenika/207
Accept: application/json
###

POST {{MmorpgApi_HostAddress}}/Svestenik/DodajSvestenika/{{LikId}} HTTP/1.1
content-type: application/json

{
  "religija": "Luminism",
  "blagoslovi": "Healing",
  "canHeal": 1
}
###

PUT {{MmorpgApi_HostAddress}}/Svestenik/AzurirajSvestenika/ HTTP/1.1
Content-Type: application/json

{
  "id": 207,
  "religija": "Luminism",
  "blagoslovi": "Hurting",
  "canHeal": 0
}
###

DELETE {{MmorpgApi_HostAddress}}/Svestenik/ObrisiSvestenika/207 HTTP/1.1
Content-Type: application/json
###