@MmorpgApi_HostAddress = https://localhost:7250

GET {{MmorpgApi_HostAddress}}/Igrac/PreuzmiIgrace
Accept: application/json
###

GET {{MmorpgApi_HostAddress}}/Igrac/PreuzmiIgraca/161
Accept: application/json
###

POST {{MmorpgApi_HostAddress}}/Igrac/DodajIgraca HTTP/1.1
content-type: application/json

{
  "nadimak": "Pera",
  "lozinka": "PerinaSifra",
  "pol": "M",
  "ime": "Petar",
  "prezime": "Petrovic",
  "uzrast": 22
}
###

PUT {{MmorpgApi_HostAddress}}/Igrac/AzurirajIgraca HTTP/1.1
Content-Type: application/json

{
  "id": 261,
  "nadimak": "Pera",
  "lozinka": "MojaSifra",
  "pol": "M",
  "ime": "Petar",
  "prezime": "Petrovic",
  "uzrast": 15
}
###

DELETE {{MmorpgApi_HostAddress}}/Igrac/ObrisiIgraca/261 HTTP/1.1
Content-Type: application/json
###